---
title: "Dauer Microbiome: SourceTracker Analysis"
author: "Rahul Bodkhe"
date: "03/03/2024"
output: html_document
runAge: shiny
---

#Inputting phyloseq Object
```{r eruptions, echo=FALSE}
rm(list=ls())
library(phyloseq)
source('SourceTracker.r')
library(ggplot2)
library("reshape2")
library(ggforce)

```
```{r}
rm(list = ls())
pseq <- readRDS("../input_files/final_Object_4_analysis.rds")
taxa_names(pseq) <- paste0("SV", seq(ntaxa(pseq)))
```
```{r}
metadata <- sample_data(pseq)
metadata
```
```{r}
otus = as(otu_table(pseq), "matrix")
```
# extract only those samples in common between the two tables
```{r}
common.sample.ids <- intersect(rownames(metadata), rownames(otus))
otus <- otus[common.sample.ids,]
metadata <- metadata[common.sample.ids,]
# double-check that the mapping file and otu table
# had overlapping samples
if(length(common.sample.ids) <= 1) {
    message <- paste(sprintf('Error: there are %d sample ids in common '),
                    'between the metadata file and data table')
    stop(message)
}
```
# extract the source environments and source/sink indices
```{r}
train.ix <- which(metadata$SourceSink=='source')
test.ix <- which(metadata$SourceSink=='sink')
envs <- metadata$Env
if(is.element('Description',colnames(metadata))) desc <- metadata$Description
```
# load SourceTracker package
```{r}
source('SourceTracker.r')
```
#NOTE skipping tuning
```{r}
alpha1 <- alpha2 <- 0.001
```
# train SourceTracker object on training data
```{r}
st <- sourcetracker(otus[train.ix,], envs[train.ix])
```

# Estimate source proportions in test data
```{r}
results <- predict(st,otus[test.ix,], alpha1=alpha1, alpha2=alpha2)
```

# Estimate leave-one-out source proportions in training data 
```{r}
results.train <- predict(st, alpha1=alpha1, alpha2=alpha2)
```
# plot results
```{r}
labels <- sprintf('%s %s', envs,desc)
plot(results, labels[test.ix], type='pie')
plot(results, labels[test.ix], type='bar')
plot(results, labels[test.ix], type='dist')
plot(results.train, labels[train.ix], type='pie')
plot(results.train, labels[train.ix], type='bar')
plot(results.train, labels[train.ix], type='dist')

# plot results with legend
plot(results, labels[test.ix], type='pie', include.legend=TRUE, env.colors=c("#33ff33",  "#00cccc","#006666","#ff66ff", "darkblue","grey71","#4B0082","#fb9a99","#FF00FF","dodgerblue3","darkgoldenrod1"))
```

```{r}
env.colors=c("#006666", "#00cccc","darkblue","#ff66ff", "#800000","grey71", "#fb9a99","#FF00FF","dodgerblue3","darkgoldenrod1")
downstream <- data.frame(results$proportions)
downstream$id <- row.names(downstream)
meltdown <- melt(downstream, id.vars=c("id"))
write.csv(meltdown, "final.csv")
p<- ggplot(meltdown, aes(x=id, y = value)) + geom_bar(aes(fill = variable), stat="identity")+
  scale_fill_manual(values= env.colors) + theme(panel.grid.major = element_blank()) +  theme(strip.text.x = element_text(size =12)) +theme(text = element_text(size=16),axis.text.y = element_text(hjust=1)) +
    scale_x_discrete(drop=TRUE) +theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))+
       guides(fill = guide_legend( keywidth = 1, keyheight = 1))  + theme(axis.text = element_text(face="bold"))
p +   theme(panel.grid.major = element_blank()) +  theme(strip.text.x = element_text(size =12))
p
ggsave("final.png", height = 6, width = 6)
```